export const TRANSACTION_LIMITS = {
  MAX_WITHDRAWAL_PER_TRANSACTION: 200,
  MAX_DAILY_WITHDRAWAL: 400,
  WITHDRAWAL_MULTIPLE: 5,
  MAX_DEPOSIT_PER_TRANSACTION: 1000,
  MIN_POSITIVE_AMOUNT: 0,
} as const;
